config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  devise_for :users
  get '/search', to: 'searchs#search'
  resources :users, only: [:show, :index, :edit, :update]  do
   resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers', as: 'followers'
 end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 belongs_to :user
 has_many :book_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :favorites_user, through: :favorites, source: :user

 validates :title, presence: true
 validates :body, presence: true, length: { maximum: 200 } 
 
 def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
 end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
 belongs_to :follower, class_name: "User"
 belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_book, through: :favorites, source: :book 
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
 def follow(user_id)
    relationships.create(followed_id: user_id)
 end

 def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
 end
  
 def following?(user)
    followings.include?(user)
 end
  
  attachment :profile_image
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 } 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def index
    @books = Book.includes(:favorites_user).sort {|a,b| b.favorites_user.size <=> a.favorites_user.size}
    @user = current_user
    @book = Book.new
    @book_comment = BookComment.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "successfully"
    redirect_to book_path(@book.id)
    else
     @books = Book.all
     @user = current_user
     render("books/index")
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = current_user
    @book_comment = BookComment.new
    
  end
  
  def edit
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to  books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
    flash[:notice] = "successfully"
    redirect_to book_path(@book.id)
    else
     @user = current_user
     render("books/edit")
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
 private

  def book_params
  params.require(:book).permit(:title, :body)
  end
  
  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
 def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
 end

 def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
 end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
   @users = User.all
   @user = current_user
   
   @book = Book.new
   @followings = @user.followings
   @followers = @user.followers
   
  end
  
  def show
   @user = User.find(params[:id])
   @books = @user.books
   @book = Book.new
   @followings = @user.followings
   @followers = @user.followers
   @currentUserEntry=Entry.where(user_id: current_user.id)
   @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end 
  
  def edit
   @user = User.find(params[:id])
   unless @user == current_user
      redirect_to  user_path(current_user.id)
   end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "successfully"
    redirect_to user_path(@user.id)  
    else
    render("users/edit")
    end
  end
  
  
 private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr id="book_<%= book.id %>">
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class="favorite-btn"><%= render "favorites/favorite-btn", book: book %></td>
        <td>コメント数: <%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_result.html.erb
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>title</th>
            <th>opinion</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody id="book">
    <% books.each do |book| %>
      <tr>
        <td><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" , size:'40x40' %></td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
        <% if book.user == current_user %>
          <td><%= link_to "Edit", edit_book_path(book) %></td>
          <td><%= link_to "Destroy", book_path(book), method: :delete, remote: true %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container pt-3">
  <div class="row">
      <div class="col-5 px-5">
<h2>Editing Book</h2>
<%= form_with model:@book, local: true do |f| %>
  <label for="inputTitle">Title</label><br>
  <%= f.text_field :title, autofocus: true, class: 'form-control w-100' %><br>
  <label for="inputOpinion">Opinion</label><br>
  <%= f.text_area :body, autofocus: true, class: 'form-control w-100'%><br>
  
  <%= f.submit 'Update Book', class: 'btn btn-success mt-3' %>
<% end %><br>
<%= link_to "Show", book_path(@book.id) %>|<%= link_to "Back", books_path %>

</div>
</div>
</div>

app/views/books/index.html.erb
 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container pt-3">
  <div class="row">
   <div class="col-md-3">
    <h2>User info</h2>
     <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100'%>
     <table class="table">
      <tr><th>name</th>
      <td><%= @user.name %></td></tr>
      <tr><th>introduction</th>
      <td><%= @user.introduction %></td></tr>
      <tr>
        <th>follows</th>
        <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
       </tr>
       <tr>
        <th>followers</th>
        <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
       </tr>
     </table>
     
     <%= link_to  edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block", method: :get do %>
     <i class="fas fa-user-cog" ></i>
     <% end %>
     
     

    <h2 class="mt-3">New book</h2>
     <%= form_with model: @book, local:true do |f| %>
     <p>Title</p>
     <%= f.text_field :title, class: "w-100" %>
     <p>Opinion</p>
     <%= f.text_field :body, class: "w-100"%></br>
     <%= f.submit 'Create Book', class: 'btn btn-success mt-3' %>
     <% end %>
   </div>

  <div class="col-md-8 offset-md-1">
   <%= render 'searchs/form' %><br>
   <h2>Books</h2>
    <%= render 'index', books: @books%>
  </div>
 </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_field :opinion %>
   <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
     <p class="notice">
       <%= flash[:notice] %>
     </p>
 <% end %>
 
<% if @book_comment.errors.any? %>
  <% @book_comment.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container pt-3">
 <div class="row">
  <div class="col-md-3">
  <h2>User info</h2>
   <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %>
    <table class="table">
     <tr><th>name</th>
     <td><%= @book.user.name %></td></tr>
     <tr><th>introduction</th>
     <td><%= @book.user.introduction %></td></tr>
     <tr>
      <th>follows</th>
      <th><%= link_to @book.user.followings.count, user_followings_path(@book.user) %></th>
     </tr>
      <tr>
      <th>followers</th>
      <th><%= link_to @book.user.followers.count, user_followers_path(@book.user) %></th>
     </tr>
   </table>
   
   
    <% if @book.user.id == current_user.id %>
      <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog" ></i><% end %>
     
     <% elsif current_user.following?(@book.user) %>
      <%= link_to "フォローを外す", user_relationships_path(@book.user.id), method: :delete, class: "btn btn-primary btn-block" %>
       <% else %>
         <%= link_to "フォローする", user_relationships_path(@book.user.id), method: :post, class: "btn btn-success btn-block" %>
      <% end %>
  
  <h2 class="mt-3">New book</h2>
   <%= form_with model: @book_new, local: true do |f| %>
   <p>Title</p>
   <%= f.text_field :title, class: "w-100" %>
   <p>Opinion</p>
   <%= f.text_field :body, class: "w-100" %>
   <%= f.submit 'Create Book', class: 'btn btn-success mt-3' %>
   <% end %>
  </div>

<div class="col-md-8 offset-md-1">
 <h2>Book detail</h2>
  <table class="table">
   <tr id="book_<%= @book.id %>">
    <td><%= link_to user_path(@book.user) do %>
         <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" , size:'40x40' %><br>
         <%= @book.user.name %> </td>
         <% end %>
    <td><%= link_to @book.title, book_path(@book.id) %></td>
    <td><%= @book.body %></td>
    <td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>
    <td class="comments-count">コメント数: <%= @book.book_comments.count %></td>
     <% if @book.user == current_user %>
    <td><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-success' %></td>
    <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: 'btn btn-danger' %></td>
    </tr>
    <% end %>
   </table>
   <table class="book_comments">
   <%= render 'book_comments/comment', book: @book %>
   </table>
   
   <div class="new-comment">
     <%= form_with model:[@book, @book_comment] do |f| %>
     <%= f.text_area :comment, class: 'w-100' %>
     <%= f.submit "送信" %>
     <% end %>
    </div>
   </div>
 </div>
</div>

app/views/rooms/show.html.erb
<div class="container pt-3">

<hr>
<% if @messages.present? %>
  <% @messages.each do |m| %>
    <strong><%= m.content %></strong>
    <small>by <strong>
    <%= attachment_image_tag m.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'30x30' %>
    <a href="/users/
    <%= m.user_id %>"><%= m.user.name %>さん</a></strong></small>
    <hr>
  <% end %>
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>

<%= form_with model: @message do |f| %>
  <%= f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  
  <%= f.submit "投稿する" %>
<% end %>
<br>

<%= link_to "戻る", users_path %>

</div>

app/views/users/_result.html.erb
<table class="table">
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
        </tr>
    </thead>
    <tbody id="user">
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" , size:'40x40' %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container pt-3 d-flex align-items-center justify-content-center">
  <div class="row">
      <div class="col-12">

<h2>User info</h2>
<%= form_with model:@user, local:true do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name, autofocus: true, class: "w-100" %>
  <br>
  <%= f.label :image %>
  <br>
  <%= f.attachment_field :profile_image %>
  <br>
  <%= f.label :introduction %>
  <br>
  <%= f.text_area :introduction, class: "w-100" %>
  <br>

  <%= f.submit "Update User", class: 'btn btn-secondary mt-3' %>
<% end %>

</div>
</div>
</div>

app/views/users/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container pt-3">
 <div class="row">
   <div class="col-md-3">
     <h2> User info</h2>
     <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %>
     <table class="table">
      
       <tr>
        <th>name</th>
        <th><%= @user.name %></th>
       </tr>
       <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
       </tr>
       <tr>
        <th>follows</th>
        <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
       </tr>
       <tr>
        <th>followers</th>
        <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
       </tr>
     </table>
     
     <% if @user.id == current_user.id %>
      <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog" ></i><% end %>
     
     <% else %>
      <%= link_to user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog" ></i>
      <% end %>
     <% end %>
     
    <h2 class="mt-3">New book</h2>
     <%= form_with model: @book, local:true do |f| %>
       <p>Title</p>
       <%= f.text_field :title, class: "w-100" %>
       <p>Opinion</p>
       <%= f.text_field :body, class: "w-100" %>
       <%= f.submit 'Create Book', class: 'btn btn-success mt-3' %>
     <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
     <%= render 'searchs/form' %><br>
      <h2>Users</h2>
      <table class="table">
       <thead>
        <tr>
         <th>image</th>
         <th>name</th>
         <th colspan="3"></th>
        </tr>
       </thead>
       <tbody>
       <% @users.each do |user| %>
         <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" , size:'40x40' %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><% if current_user != user %>
          <% if current_user.following?(user) %>
          <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
          <% end %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
         </tr>
      <% end %>
     </table>
     </tbody>
    </div>
   </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p class="notice">
    <%= flash[:notice] %>
  </p>
 <% end %>
 
<div class="container pt-3">
 <div class="row">
   
  <div class="col-md-3">
  <h2>User info</h2>
   <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
   <table class="table">
     <tr>
       <th>name</th>
       <th><%= @user.name %></th>
      </tr>
     <tr>
       <th>introduction</th>
       <th><%= @user.introduction %></th>
     </tr>
     <tr>
      <th>follows</th>
      <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
     </tr>
      <tr>
      <th>followers</th>
      <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
     </tr>
   </table>
    
     <% if @user.id == current_user.id %>
      <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog" ></i><% end %>
     
     <% elsif current_user.following?(@user) %>
      <%= link_to "フォローを外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-primary btn-block" %><br>
      
     <% unless @user.id == current_user.id %>
   　　<% if @isRoom == true %>
     　<%= link_to "チャット", room_path(@roomId), class: "btn btn-secondary btn-block" %>
   　　<% else %>
     　<%= form_with model: @room, local: true do |f|%>
       <%= fields_for @entry do |r| %>
         <%= r.hidden_field :user_id, value: @user.id %>
       <% end %>
       <%= f.submit "チャットを始める", class: "btn btn-secondary btn-block" %>
     　<% end %>
   　　<% end %>
　　 <% end %>
       
     <% else %>
         <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-success btn-block" %>
      <% end %>
      
  <h2 class="mt-3">New book</h2>
   <%= form_with model: @book, local:true do |f| %>
     <p>Title</p>
     <%= f.text_field :title, class: "w-100" %>
     <p>Opinion</p>
     <%= f.text_field :body, class: "w-100" %>
     <%= f.submit 'Create Book', class: 'btn btn-success mt-3' %>
   <% end %>
  </div>
 
 <div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table">
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user.id) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" , size:'40x40' %></td><% end %>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
    </table>
  </div>
  
 </div>
</div>