config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  devise_for :users
  get '/search', to: 'searchs#search'
  resources :users, only: [:show, :index, :edit, :update]  do
   resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers', as: 'followers'
 end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 belongs_to :user
 has_many :book_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :favorites_user, through: :favorites, source: :user

 validates :title, presence: true
 validates :body, presence: true, length: { maximum: 200 } 
 
 def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
 end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
 belongs_to :follower, class_name: "User"
 belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_book, through: :favorites, source: :book 
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
 def follow(user_id)
    relationships.create(followed_id: user_id)
 end

 def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
 end
  
 def following?(user)
    followings.include?(user)
 end
  
  attachment :profile_image
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 } 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def index
    @books = Book.includes(:favorites_user).sort {|a,b| b.favorites_user.size <=> a.favorites_user.size}
    @user = current_user
    @book = Book.new
    @book_comment = BookComment.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "successfully"
    redirect_to book_path(@book.id)
    else
     @books = Book.all
     @user = current_user
     render("books/index")
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = current_user
    @book_comment = BookComment.new
    
  end
  
  def edit
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to  books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
    flash[:notice] = "successfully"
    redirect_to book_path(@book.id)
    else
     @user = current_user
     render("books/edit")
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
 private

  def book_params
  params.require(:book).permit(:title, :body)
  end
  
  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
 def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
 end

 def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
 end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- FontAwesomeの読み込み -->
    <script src="https://kit.fontawesome.com/3343b9fe07.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to " Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to " Users", users_path, class: 'fas fa-users nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to " Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>
            
            <% else %>
            <li class="nav-item">
              <%= link_to " Home", root_path, class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to " About", home_about_path, class: 'fas fa-link nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <footer class="">CopyRight Infratop.inc</footer>
     </div>
    </div>
  </div>
    
  </body>
</html>